baseURL: https://spiritualites.ch/
title: "Spiritualités protestantes"
defaultContentLanguage: fr
languageCode: fr-ch

googleAnalytics: UA-131329337-5
enableRobotsTXT: true

disableFastRender: true

params:
  title: Spiritualités protestantes
  description: Blog sur les offres spirituelles et méditatives réformées en Suisse romande
  email: hello@nicolasfriedli.ch
  author: 
    name: Nicolas Friedli
    url: https://nicolasfriedli.ch
  images:
    - /img/spiritualite.jpg
    - /img/spiritualites-1.jpg
    - /img/spiritualites-2.jpg
    - /img/spiritualites-3.jpg
    - /img/spiritualites-4.jpg
    - /img/spiritualites-5.jpg

disableKinds:
  - taxonomy
  - taxonomyTerm
  - section

taxonomies:
  tag: tags

# Repris de https://github.com/jamstatic/jamstatic-fr/blob/21e1888dc2b174176a6e9761bb86438b91f5e15e/config.yaml
related:
  threshold: 60
  includeNewer: true
  toLower: false
  indices:
    - name: "keywords" 
      weight: 80
    - name : "date"
      weight: 20
      pattern: "2006"